
apiVersion: v2
appVersion: 2.4.1
dependencies:
  - condition: vsphere-cpi.enabled
    name: vsphere-cpi
    repository: https://vsphere-tmm.github.io/helm-charts
    version: 1.x.x
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: A Helm chart for vSphere CSI Driver
engine: gotpl
home: https://github.com/kubernetes-sigs/vsphere-csi-driverhttps://github.com/kubernetes-sigs/vsphere-csi-driver
icon: https://raw.githubusercontent.com/kubernetes-sigs/vsphere-csi-driver/master/docs/images/vmware_logo.png
keywords:
  - vsphere
  - vmware
  - csi
maintainers:
  - name: Maximilian Rink
    email: maximilian.rink@telekom.de
  - name: Myles Gray
    email: myles@vmware.com
name: vsphere-csi
sources:
  - https://github.com/kubernetes-sigs/vsphere-csi-driver
version: 1.3.2
