annotations:
  category: cpi
apiVersion: v2
appVersion: v1.25.1
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
description: Helm chart for the vSphere-CPI
engine: gotpl
home: https://github.com/kubernetes/cloud-provider-vsphere
keywords:
  - vSphere
  - CPI
maintainers:
  - name: Maximilian Rink
    email: maximilian.rink@telekom.de
  - name: Myles Gray
    email: myles@vmware.com
name: vsphere-cpi
sources:
version: 1.5.0
